"""add_slug_to_products

Revision ID: 2c31e25ed497
Revises: 02592f27c634
Create Date: 2026-07-31 11:21:50.980142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c31e25ed497'
down_revision: Union[str, None] = '02592f27c634'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('download_tokens_token_key', 'download_tokens', type_='unique')
    op.drop_constraint('orders_order_number_key', 'orders', type_='unique')
    op.add_column('products', sa.Column('slug', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_products_slug'), 'products', ['slug'], unique=True)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_wallet_address_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_wallet_address_key', 'users', ['wallet_address'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_index(op.f('ix_products_slug'), table_name='products')
    op.drop_column('products', 'slug')
    op.create_unique_constraint('orders_order_number_key', 'orders', ['order_number'])
    op.create_unique_constraint('download_tokens_token_key', 'download_tokens', ['token'])
    # ### end Alembic commands ###
